/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import Bescovitch.Geometry.Basic

/-!
# Oriented coordinates in the Euclidean plane

The quarter turn of a unit vector completes it to an orthonormal basis.  These elementary
identities let the mixed six-point argument use coordinates relative to its root direction.
-/

@[expose] public section

noncomputable section

open scoped InnerProductSpace

namespace Bescovitch

/-- Counterclockwise rotation through a right angle. -/
def quarterTurn (x : Plane) : Plane :=
  !₂[-x 1, x 0]

@[simp]
theorem quarterTurn_apply_zero (x : Plane) : quarterTurn x 0 = -x 1 := by
  rfl

@[simp]
theorem quarterTurn_apply_one (x : Plane) : quarterTurn x 1 = x 0 := by
  rfl

/-- A quarter turn preserves the Euclidean norm. -/
@[simp]
theorem norm_quarterTurn (x : Plane) : ‖quarterTurn x‖ = ‖x‖ := by
  rw [← sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)]
  simp [EuclideanSpace.real_norm_sq_eq, quarterTurn, add_comm]

/-- A vector is orthogonal to its quarter turn. -/
@[simp]
theorem real_inner_quarterTurn_self (x : Plane) : ⟪quarterTurn x, x⟫_ℝ = 0 := by
  simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
  ring

/-- A vector is also orthogonal to its quarter turn in the opposite order. -/
@[simp]
theorem real_inner_self_quarterTurn (x : Plane) : ⟪x, quarterTurn x⟫_ℝ = 0 := by
  rw [real_inner_comm]
  exact real_inner_quarterTurn_self x

/-- Coordinates in the orthonormal frame generated by a unit vector reconstruct the vector. -/
theorem plane_eq_inner_smul_add_inner_quarterTurn_smul (e x : Plane) (he : ‖e‖ = 1) :
    x = ⟪e, x⟫_ℝ • e + ⟪quarterTurn e, x⟫_ℝ • quarterTurn e := by
  have heSq : e 0 ^ 2 + e 1 ^ 2 = 1 := by
    have h := congrArg (fun r : ℝ ↦ r ^ 2) he
    simpa [EuclideanSpace.real_norm_sq_eq, Fin.sum_univ_two] using h
  ext i
  fin_cases i
  · simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
    symm
    calc
      _ = x 0 * (e 0 ^ 2 + e 1 ^ 2) := by ring
      _ = x 0 := by rw [heSq]; ring
  · simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
    symm
    calc
      _ = x 1 * (e 0 ^ 2 + e 1 ^ 2) := by ring
      _ = x 1 := by rw [heSq]; ring

/-- The squared norm is the sum of the squares of the two oriented coordinates. -/
theorem norm_sq_eq_inner_sq_add_inner_quarterTurn_sq (e x : Plane) (he : ‖e‖ = 1) :
    ‖x‖ ^ 2 = ⟪e, x⟫_ℝ ^ 2 + ⟪quarterTurn e, x⟫_ℝ ^ 2 := by
  have heSq : e 0 ^ 2 + e 1 ^ 2 = 1 := by
    have h := congrArg (fun r : ℝ ↦ r ^ 2) he
    simpa [EuclideanSpace.real_norm_sq_eq, Fin.sum_univ_two] using h
  simp [EuclideanSpace.real_norm_sq_eq, PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
  calc
    x 0 ^ 2 + x 1 ^ 2 = (x 0 ^ 2 + x 1 ^ 2) * (e 0 ^ 2 + e 1 ^ 2) := by
      rw [heSq]
      ring
    _ = (x 0 * e 0 + x 1 * e 1) ^ 2 +
        (-(x 0 * e 1) + x 1 * e 0) ^ 2 := by ring

end Bescovitch
