/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import Bescovitch.Statement

/-!
# Oriented coordinates in the Euclidean plane

The quarter turn of a unit vector completes it to an orthonormal basis.  These elementary
identities let the mixed six-point argument use coordinates relative to its root direction.
-/

@[expose] public section

noncomputable section

open scoped InnerProductSpace

namespace Bescovitch

/-- Counterclockwise rotation through a right angle. -/
def quarterTurn (x : (EuclideanSpace ℝ (Fin 2))) : (EuclideanSpace ℝ (Fin 2)) :=
  !₂[-x 1, x 0]

@[simp]
theorem quarterTurn_apply_zero (x : (EuclideanSpace ℝ (Fin 2))) : quarterTurn x 0 = -x 1 := by
  rfl

@[simp]
theorem quarterTurn_apply_one (x : (EuclideanSpace ℝ (Fin 2))) : quarterTurn x 1 = x 0 := by
  rfl

/-- A quarter turn preserves the Euclidean norm. -/
@[simp]
theorem norm_quarterTurn (x : (EuclideanSpace ℝ (Fin 2))) : ‖quarterTurn x‖ = ‖x‖ := by
  rw [← sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)]
  simp [EuclideanSpace.real_norm_sq_eq, quarterTurn, add_comm]

/-- A vector is orthogonal to its quarter turn. -/
@[simp]
theorem real_inner_quarterTurn_self (x : (EuclideanSpace ℝ (Fin 2))) : ⟪quarterTurn x, x⟫_ℝ = 0 := by
  simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
  ring

/-- A vector is also orthogonal to its quarter turn in the opposite order. -/
@[simp]
theorem real_inner_self_quarterTurn (x : (EuclideanSpace ℝ (Fin 2))) : ⟪x, quarterTurn x⟫_ℝ = 0 := by
  rw [real_inner_comm]
  exact real_inner_quarterTurn_self x

/-- Coordinates in the orthonormal frame generated by a unit vector reconstruct the vector. -/
theorem plane_eq_inner_smul_add_inner_quarterTurn_smul (e x : (EuclideanSpace ℝ (Fin 2))) (he : ‖e‖ = 1) :
    x = ⟪e, x⟫_ℝ • e + ⟪quarterTurn e, x⟫_ℝ • quarterTurn e := by
  have heSq : e 0 ^ 2 + e 1 ^ 2 = 1 := by
    have h := congrArg (fun r : ℝ ↦ r ^ 2) he
    simpa [EuclideanSpace.real_norm_sq_eq, Fin.sum_univ_two] using h
  ext i
  fin_cases i
  · simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
    symm
    calc
      _ = x 0 * (e 0 ^ 2 + e 1 ^ 2) := by ring
      _ = x 0 := by rw [heSq]; ring
  · simp [PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
    symm
    calc
      _ = x 1 * (e 0 ^ 2 + e 1 ^ 2) := by ring
      _ = x 1 := by rw [heSq]; ring

/-- The squared norm is the sum of the squares of the two oriented coordinates. -/
theorem norm_sq_eq_inner_sq_add_inner_quarterTurn_sq (e x : (EuclideanSpace ℝ (Fin 2))) (he : ‖e‖ = 1) :
    ‖x‖ ^ 2 = ⟪e, x⟫_ℝ ^ 2 + ⟪quarterTurn e, x⟫_ℝ ^ 2 := by
  have heSq : e 0 ^ 2 + e 1 ^ 2 = 1 := by
    have h := congrArg (fun r : ℝ ↦ r ^ 2) he
    simpa [EuclideanSpace.real_norm_sq_eq, Fin.sum_univ_two] using h
  simp [EuclideanSpace.real_norm_sq_eq, PiLp.inner_apply, quarterTurn, Fin.sum_univ_two]
  calc
    x 0 ^ 2 + x 1 ^ 2 = (x 0 ^ 2 + x 1 ^ 2) * (e 0 ^ 2 + e 1 ^ 2) := by
      rw [heSq]
      ring
    _ = (x 0 * e 0 + x 1 * e 1) ^ 2 +
        (-(x 0 * e 1) + x 1 * e 0) ^ 2 := by ring

/-- Coordinates relative to a unit first axis, with either choice of transverse orientation. -/
def orientedCoordinates (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (x : (EuclideanSpace ℝ (Fin 2))) : (EuclideanSpace ℝ (Fin 2)) :=
  !₂[⟪e, x⟫_ℝ, orientation * ⟪quarterTurn e, x⟫_ℝ]

@[simp]
theorem orientedCoordinates_apply_zero (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (x : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinates e orientation x 0 = ⟪e, x⟫_ℝ := by
  rfl

@[simp]
theorem orientedCoordinates_apply_one (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (x : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinates e orientation x 1 = orientation * ⟪quarterTurn e, x⟫_ℝ := by
  rfl

/-- Oriented coordinates preserve norms when the first axis is unit and the orientation is a
sign. -/
theorem norm_orientedCoordinates (e : (EuclideanSpace ℝ (Fin 2))) {orientation : ℝ} (x : (EuclideanSpace ℝ (Fin 2)))
    (he : ‖e‖ = 1) (horientation : orientation ^ 2 = 1) :
    ‖orientedCoordinates e orientation x‖ = ‖x‖ := by
  rw [← sq_eq_sq₀ (norm_nonneg _) (norm_nonneg _)]
  rw [norm_sq_eq_inner_sq_add_inner_quarterTurn_sq e x he]
  simp only [EuclideanSpace.real_norm_sq_eq, orientedCoordinates, Fin.sum_univ_two,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  nlinarith

@[simp]
theorem orientedCoordinates_add (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (x y : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinates e orientation (x + y) =
      orientedCoordinates e orientation x + orientedCoordinates e orientation y := by
  ext i
  fin_cases i
  · simp [orientedCoordinates, inner_add_right]
  · simp [orientedCoordinates, inner_add_right]
    ring

@[simp]
theorem orientedCoordinates_sub (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (x y : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinates e orientation (x - y) =
      orientedCoordinates e orientation x - orientedCoordinates e orientation y := by
  ext i
  fin_cases i
  · simp [orientedCoordinates, inner_sub_right]
  · simp [orientedCoordinates, inner_sub_right]
    ring

@[simp]
theorem orientedCoordinates_smul (e : (EuclideanSpace ℝ (Fin 2))) (orientation a : ℝ) (x : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinates e orientation (a • x) = a • orientedCoordinates e orientation x := by
  ext i
  fin_cases i
  · simp [orientedCoordinates, real_inner_smul_right]
  · simp [orientedCoordinates, real_inner_smul_right]
    ring

/-- The chosen unit first axis has coordinates `(1,0)`. -/
theorem orientedCoordinates_self (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (he : ‖e‖ = 1) :
    orientedCoordinates e orientation e = !₂[1, 0] := by
  ext i
  fin_cases i
  · simp [orientedCoordinates, he]
  · simp [orientedCoordinates]

/-- Taking oriented coordinates is a linear isometry. -/
def orientedCoordinateIsometry (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (he : ‖e‖ = 1)
    (horientation : orientation ^ 2 = 1) : (EuclideanSpace ℝ (Fin 2)) →ₗᵢ[ℝ] (EuclideanSpace ℝ (Fin 2)) where
  toFun := orientedCoordinates e orientation
  map_add' := orientedCoordinates_add e orientation
  map_smul' := orientedCoordinates_smul e orientation
  norm_map' := fun x ↦ norm_orientedCoordinates e x he horientation

@[simp]
theorem orientedCoordinateIsometry_apply (e : (EuclideanSpace ℝ (Fin 2))) (orientation : ℝ) (he : ‖e‖ = 1)
    (horientation : orientation ^ 2 = 1) (x : (EuclideanSpace ℝ (Fin 2))) :
    orientedCoordinateIsometry e orientation he horientation x =
      orientedCoordinates e orientation x := by
  rfl

end Bescovitch
